### ISSUE TITLE
Attached SVG render to PNG hangs

### ISSUE THREAD

**Issue by Dimigergo** [svg-net/SVG#1013]
#### Description
If I use this code with the attached sample svg, the svgDocument.Draw() hangs infinite, and does not any output. The processor runs is in 10-15% (CORE vPRO i7), the memory does not increase stay at 50-55 Mb. I wait for 30 minutes without any result or any exception.
The same result if I set  the size 100x100 or 100 and 0.
```
SvgDocument svgDocument = SvgDocument.Open("Dunaferr.svg");
svgDocument.Width = 962;
svgDocument.Height = 962;

using (Bitmap bitmap = svgDocument.Draw())
    bitmap?.Save("valami.png");
```

#### Example data
[Dunaferr.zip](https://github.com/svg-net/SVG/files/9745097/Dunaferr.zip)

#### Used Versions
Project: net6
Svg: 3.4.3

**Comment by mrbean-bremen** [comment]
Fixed with #1022
