### ISSUE TITLE
Incorrect transformation into PNG (Black overlaying Boxes in PNG)

### ISSUE THREAD

**Issue by RedCali** [svg-net/SVG#1031]
#### Description
Convert an SVG into PNG leads into an PNG with black boxes overlay on other elements.  
The PNG was made with "https://inkscape.org/" where those boxes are not visible.

#### Example data
Source SVG:  
![concept](https://user-images.githubusercontent.com/36916361/211485481-8103635a-4750-4859-b6bb-508aefe7f39e.svg)

Source packed in ZIP:
[concept.svg.zip](https://github.com/svg-net/SVG/files/10409316/concept.svg.zip)

Result PNG:  
![concept](https://user-images.githubusercontent.com/36916361/211485490-5b8dd204-2483-48b3-bf7c-7f4917f6436a.png)

Screenshot Chrome Browser (Version 108.0.5359.125):  
![image](https://user-images.githubusercontent.com/36916361/211491887-a1822754-30b2-49b9-9fcc-2a8933e9b1fb.png)

Screenshot Edge Browser (Version 108.0.1462.76):  
![image](https://user-images.githubusercontent.com/36916361/211492247-3eb24383-559f-4af9-a508-572f3f9e0084.png)

#### Used Versions
- Svg.3.4.0
- Microsoft .NET   V 6.0.12 
- Win 10 Enter. / 21H2 / 19044.2251

#### Code snipped

```C#
private static string ConvertSvgToPng(string path)
        {
            // Create PNG Image from SVG-File
            var svgDocument = SvgDocument.Open(path);
            svgDocument.ShapeRendering = SvgShapeRendering.Auto;
            svgDocument.FillRule = SvgFillRule.Inherit;
            //svgDocument.FillOpacity = 1;

            Bitmap bmp = svgDocument.Draw();

            path = path.Replace(".svg", ".png");
            bmp.Save(path, ImageFormat.Png);
            return path;
        }
```

**Comment by mrbean-bremen** [comment]
Looking at your PNG in a browser (Chrome or Firefox) also shows these boxes, so I guess this could be some problem with the SVG itself...

**Comment by RedCali** [comment]
You are absolutely right, Chrome shows as well those boxes, while Edge doesn't show them.  
Just attached to screenshots from both browsers and extend the Description.

Any idea how to identify the the problem inside the SVG or if there is an option in SVG-net  to solve?

**Comment by RedCali** [comment]
indeed, that's of course strange that it displayed different in some tools... 
my guess is, that's a similar behavior with HTML in different browsers.

**Comment by mrbean-bremen** [comment]
I tried again, and as soon as I save your image to disk, I cannot reproduce the problem - it shows correctly in all browsers and in the SVG viewer. I suspect that some correction is done while saving, but I have no idea why that happens, and what exactly happens.

**Comment by RedCali** [comment]
THX for your efforts and testing  
Have you tried it with the snipped mentioned or with your own code fragment?  
i guess you're using the latest version of SVG?

**Comment by mrbean-bremen** [comment]
I checked with my own code, but I can have another look tonight - I didn't have much time yesterday, so I may not have tested the right thing. And yes, I used the latest version.

**Comment by H1Gdev** [comment]
The following error is displayed in Development tool.
```
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-2n/Bb89SPcU1jjmmeqY5KIgcpt4u+NZFBq4bNA8J+A8='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by mrbean-bremen** [comment]
I tested again, using your code snippet, and got the same output (e.g. the correct image). Can you pack your svg in a zip file and attach this to the issue? Just to be sure that the downloaded svg is really the same.

**Comment by RedCali** [comment]
> I tested again, using your code snippet, and got the same output (e.g. the correct image). Can you pack your svg in a zip file and attach this to the issue? Just to be sure that the downloaded svg is really the same.

I will as well test further in the afternoon.  
Attached the SVG packed in a zip.  
[concept.svg.zip](https://github.com/svg-net/SVG/files/10409315/concept.svg.zip)

**Comment by RedCali** [comment]
i'm not sure what it did not read in the commits between the latest and my used version (3.4.0), i thought there was nothing done towards that case as far is i read the commits made.

It seems to me that the issue is any how fixed for the problem with the latest release.

With V3.4.4 i can not reproduce the error any more....
Sorry for any inconvenience and thank you all for you're quick reaction and help, I close the issue as i don't need any more Help and the problem do not exist any more.
