### ISSUE TITLE
Bounds data error for g elements containing horizontal and vertical line segments

### ISSUE THREAD

**Issue by flyfire-cn** [svg-net/SVG#1049]
#### Description
An Svg document has a g element that contains horizontal and vertical line segments

var bmp = svgDocument.Draw();
g.DrawImage(bmp,0,0);

The above code renders the rendering correctly

RectangleF bounds = visualElement.Bounds;
bounds = {X = 0 Y = 0 Width = 0 Height = 0}

bounds data error.

#### Example data

    <g style="stroke:#00fff0;" transform="matrix(1,0,0,1,0,0)">
        <line x1="50" y1="50" x2="50" y2="20" style="stroke-width:2;"/>
        <line x1="30" y1="50" x2="70" y2="50" style="stroke-width:2;"/>
        <line x1="40" y1="60" x2="60" y2="60" style="stroke-width:2;"/>
        <line x1="45" y1="70" x2="55" y2="70" style="stroke-width:2;"/>
    </g>

#### Used Versions
Svg3.4.4
net6.0-windows

**Comment by flyfire-cn** [comment]
> RectangleF bounds = visualElement.Bounds;
> bounds = {X = 0 Y = 0 Width = 0 Height = 0}

Thank you for your reply.
The results of the above reply are incorrect.

`            foreach (SvgElement element in svgDocument.Children)
            {
                if (element is SvgVisualElement visualElement)
                {
                    RectangleF bounds = visualElement.Bounds;
                    Trace.WriteLine($"bounds:{bounds}");
                    //bounds = { X = 0 Y = 0 Width = 0 Height = 0}
                }
            }
`

**Comment by H1Gdev** [comment]
@flyfire-cn 

You can get Bounds by calling the following methods.
```cs
svgDocument.InvalidateChildPaths();
```

**Comment by flyfire-cn** [comment]
> @flyfire-cn
> 
> You can get Bounds by calling the following methods.
> 
> ```cs
> svgDocument.InvalidateChildPaths();
> ```

Thank you. That solves my problem.
