### ISSUE TITLE
Linker/AOT-incompatible code

### ISSUE THREAD

**Issue by charlesroddie** [svg-net/SVG#1061]
Reposting from https://github.com/wieslawsoltes/Svg.Skia/issues/49 as the underlying issue is in this repo.

For MCVE see https://github.com/wieslawsoltes/Svg.Skia/issues/40#issue-666972522

Problematic line of code: [here](https://github.com/svg-net/SVG/blob/7f72d36d70309293adebb66e72a71ced54ce924b/Source/SvgElementFactory.cs#L269)

```
descriptor.Converter.ConvertFrom(document, CultureInfo.InvariantCulture, attributeValue)
```

Workarounds are possible to use this library with AOT projects (Android, UWP, NativeAOT).
```
<AndroidLinkSkip>Svg.Custom</AndroidLinkSkip>
```
```
<Assembly Name="System.ComponentModel.TypeConverter" Dynamic="Required All" />
```

However these workarounds, and the line of code identified, and any use of System.ComponentModel.TypeConverter, are all evil.

**Comment by paulushub** [comment]
This is `Svg.Skia` issue, should be resolved over there.
