### ISSUE TITLE
Deprecated xlink:href attributes

### ISSUE THREAD

**Issue by matyasbach** [svg-net/SVG#1062]
#### Description

When generating svg using this library, elements like `<a>` or `<use>` are generated with `xlink:href` attribute instead of just `href` (or both of them). I believe _href_ should be added as it's the standard now and newer svg tools may not support _xlink_ one.

https://www.w3.org/TR/SVG2/linking.html#XLinkRefAttrs
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href

I'd like to make PR and find all places where it's used. + possible other deprecated xlink attributes.
Should we keep `xlink:href` together with `href` or drop it? It might be needed for legacy svg viewers but on the other side it will make svgs bigger.

**Comment by mrbean-bremen** [comment]
I'm not sure. SVG2 is still a draft and not a finalized specification, and I doubt that there are viewers out there that do not support SVG1.1 anymore, so leaving it as is should not be a problem in the foreseeable future. 

OTOH, it _is_ deprecated in SVG2, and as far as browsers are concerned, I don't think we need to support old versions. If all major browsers (and SVG viewers/editors as InkScape) support this, I would consider changing it to the new version (without keeping the old one).

Would like to hear other opinions here...

**Comment by paulushub** [comment]
> Note: SVG 2 removed the need for the xlink namespace, so instead of xlink:href you should use [href](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href).

When parsing, both form could be supported. When generating, the output should be based on the SVG version. 
I think the current version supported and validated by this library is 1.1.
