### ISSUE TITLE
Problem writing a document with changed paths in it

### ISSUE THREAD

**Issue by kravchenkoandrey** [svg-net/SVG#1085]
Hello! I have a problem pretty similar to #1054. When I try to change the value of any SvgPath element of the Children collection, I can't see any changes in the saved Svg file.

#### Description

I have an original SVG file, that looks like that
![image](https://github.com/svg-net/SVG/assets/13902711/e6a9c6ee-50a6-4850-bbec-c0b0d9a00355)
I open that file, DeepCopy it's SvgPath, then make some changes to the deep copied SvgPath and after that I replace the old SvgPath with the new one:
```c#
var sampleDoc = SvgDocument.Open(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"./sample.svg"));
            
var samplePath = (SvgPath)sampleDoc.Children[1].Children[1].DeepCopy<SvgPath>();
            
var curveSegment = samplePath.PathData[1];
curveSegment.End = new PointF(0, 0);
samplePath.PathData[1] = curveSegment;
sampleDoc.Children[1].Children[1] = samplePath;

sampleDoc.Draw().Save(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"./result.png"));
sampleDoc.Write(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"./result.svg"));
``` 
After Draw().Save() call I get all changes in the saved png:
![image](https://github.com/svg-net/SVG/assets/13902711/1bf5a2d5-9eef-4f22-8c7c-0b77591d8f20)
But after Write() call I get an svg without any changes in it as a result.

#### Example data
Here's the content of the SVG file:
```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Creator: CorelDRAW 2021 (64-Bit) -->
<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="210mm" height="297mm" version="1.1" style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd"
viewBox="0 0 21000 29700"
 xmlns:xlink="http://www.w3.org/1999/xlink"
 xmlns:xodm="http://www.corel.com/coreldraw/odm/2003">
 <defs>
  <style type="text/css">
   <![CDATA[
    .str0 {stroke:#2B2A29;stroke-width:211.67;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:22.9256}
    .fil0 {fill:none}
   ]]>
  </style>
 </defs>
 <g id="Слой_x0020_1">
  <metadata id="CorelCorpID_0Corel-Layer"/>
  <path class="fil0 str0" d="M9293.5 12991.57c0,-566.45 833.55,-708.03 1265.54,-695.12 423.87,12.67 1343.69,747.06 1526.36,1222.43 338.36,880.54 229.81,1336.88 -726.87,1563.78 -536.47,127.24 -1766.55,25.66 -2068.65,-557.45 -396.86,-766.04 3.62,-653.22 3.62,-1533.64z"/>
 </g>
</svg>
``` 

#### Used Versions
Target framework: .net 6.0

**Comment by H1Gdev** [comment]
@kravchenkoandrey 

Workaround for this issue is as follows:
```cs
sampleDoc.Children[1].Children[1] = samplePath;
sampleDoc.Children[1].Nodes[3] = samplePath;
```

Elements are managed by `Children` and `Nodes`, so users has to synchronize them...
(The division between `Children` and `Nodes` is wide-ranging and difficult to fix non-destructively.)

**Comment by kravchenkoandrey** [comment]
@H1Gdev Oh, I got it. Thank you!
