### ISSUE TITLE
System.Drawing.Common has error in .net 7

### ISSUE THREAD

**Issue by abolfazlharaini** [svg-net/SVG#1090]
**Server info**
ubuntu 20.04

**Description**
DotNet version of my project was 6 and the SVG did work correct, after change version to 7, the SVG threw below exception:

**The type initializer for 'Gdip' threw an exception.**
**System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information.**

The Microsoft have a post about this issue that description this problem
https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

Please help me

**Comment by mrbean-bremen** [comment]
This is a known problem - unfortunately, still without a solution. This is also discussed in #910. So far the only workaround is to use `Svg.Skia` for drawing as mentioned by @wieslawsoltes in that issue.

**Comment by abolfazlharaini** [comment]
Ok, **Thank you**
