### ISSUE TITLE
"Parameter is not valid" exception when document misses width and/or height

### ISSUE THREAD

**Issue by wojciechsura** [svg-net/SVG#1095]
#### Description

SVG Library crashes with error "Parameter is not valid".

The cause is that the SVG contains an element of width 100% and height 100%, but the main document doesn't have width and height specified explicitly. This causes internally the width and height to be set to 0 and subsequently an attempt to set scaling to 0, 0 (which the Graphics class doesn't like too much).

However, the document does have viewbox defined and Inkscape seems to treat it as width and height when these attributes are missing. My suggestion is to use parameters from the viewbox as missing width and height.

After enforcing Inkscape to add missing attributes to the SVG, it is being rendered correctly by the library.

#### Example data

https://freesvg.org/check-mark
Attached as well.

#### Used Versions

Version 3.4.4 from nuget. Confirmed with master branch (as from 23.10.2023)

![rodentia-icons_ok](https://github.com/svg-net/SVG/assets/5938870/0509d62d-d5cd-411f-b4d7-f80f330e3890)

**Comment by sla80** [comment]
I have the same crash with famous Tiger SVG image, which is commonly used for SVG rendering tests (there is "Height" defined, but no "Width"). It crashes with SVG library versions 3.4.5 and 3.4.6. But version 3.4.4 works fine.

![tiger](https://github.com/svg-net/SVG/assets/38268769/3c6e7645-3cf6-470e-96e6-e688e0ebeb23)

**Comment by paulushub** [comment]
@sla80 I have verified your issue in the latest commits. The previous report with [check-mark](https://freesvg.org/check-mark) is fixed.
