### ISSUE TITLE
Request for release to NuGet

### ISSUE THREAD

**Issue by allansbeckman** [svg-net/SVG#1096]
#### Description

Our team uses the SVG library and would like to request for a new version of the SVG NuGet package to be released.
We are interested in getting the latest changes as the Fizzler dependency has been removed.
We have compiled the code locally, but would prefer not to maintain the code in our repository if possible.

#### Example data

N/A

#### Used Versions

3.4.4

**Comment by mrbean-bremen** [comment]
Ok, the Halloween release is out (3.4.5).
