### ISSUE TITLE
Извините но я утюг, обработка нажатия на элементы SVG

### ISSUE THREAD

**Issue by Konstantanter** [svg-net/SVG#1100]
#### Description

У меня есть изображение карты РФ, со всеми регионами, как можно понять на какой регион нажал пользователь?
обрыл просто всё.
Пишу на Xamarin:(
#### Example data

![Rus_BlackAndWhiteNotGroup](https://github.com/svg-net/SVG/assets/24816527/fd22a568-6144-4090-8f73-e0cc7ec51893)

**Comment by Konstantanter** [comment]
пытался сделать как то так
`using SkiaSharp;
using SkiaSharp.Views.Forms;
using Xamarin.Forms;

public class MapPage : ContentPage
{
    public MapPage()
    {
        var svgMap = new SKSvg();
        svgMap.Load("russia_map.svg"); // Предполагается, что у вас есть файл russia_map.svg в проекте

        var canvasView = new SKCanvasView();
        canvasView.PaintSurface += OnCanvasViewPaintSurface;

        Content = canvasView;
    }

    private void OnCanvasViewPaintSurface(object sender, SKPaintSurfaceEventArgs e)
    {
        var canvas = e.Surface.Canvas;
        canvas.Clear();

        // Рисуем карту России из SVG
        canvas.DrawPicture(svgMap.Picture);

        // Добавляем обработчики событий для нажатий на регионы
        canvasView.Touch += (touchSender, touchEvent) =>
        {
            // Определяем, на какой регион нажал пользователь
            SKPoint touchPoint = touchEvent.Location;
            if (IsPointInRegion1(touchPoint))
            {
                // Пользователь нажал на регион 1
            }
            else if (IsPointInRegion2(touchPoint))
            {
                // Пользователь нажал на регион 2
            }
            // И так далее для остальных регионов
        };
    }
}`
где
`private bool IsPointInRegion1(SKPoint point)
{
    // Предположим, что регион 1 - это прямоугольная область с координатами (x1, y1, x2, y2)
    SKRect region1Rect = new SKRect(x1, y1, x2, y2);
    return region1Rect.Contains(point);
}

//Для работы с геометрическими фигурами и определения, находится ли точка внутри конкретного региона в SkiaSharp, //вы можете использовать методы и структуры, предоставляемые самой библиотекой.

//Например, вы можете использовать методы Contains для проверки, находится ли точка внутри геометрической фигуры, такой как SKRect (прямоугольник) или SKPath (путь). Вот пример использования метода Contains для проверки точки внутри прямоугольника:

SKRect regionRect = new SKRect(x, y, width, height);
SKPoint point = new SKPoint(x, y);
bool isPointInside = regionRect.Contains(point);
Если ваши регионы имеют более сложные формы, вы можете использовать SKPath для представления контуров регионов и проверки, находится ли точка внутри контура с помощью метода Contains:

SKPath regionPath = new SKPath();
// Добавление точек и линий в путь для представления контура региона

bool isPointInside = regionPath.Contains(point);`

**Comment by mrbean-bremen** [comment]
Also note that this seems to belong to SkiaSharp, not to SVG.
