### ISSUE TITLE
Latest Nuget version can not load images - BUG

### ISSUE THREAD

**Issue by rasmus-s** [svg-net/SVG#1101]
#### Description
After upgrading from Nuget v. 3.4.4 to 3.4.5 SVG can not load images. It has been working in ALL other nuget versions.
It fails with message: `Error: 0 : Error loading image: 'https://www.w3.org/Icons/SVG/svg-logo-v.png', error: The header name 'image/svg+xml' has an invalid format.`

#### Example data

SVG
```
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100" height="100">
  <image xlink:href="https://www.w3.org/Icons/SVG/svg-logo-v.png" height="100" width="100" />
</svg>
```

Code:
```
var svgDocument = SvgDocument.Open<SvgDocument>(stream);
var bitmap = svgDocument.Draw();
```

#### Used Versions
Nuget version: [3.4.5](https://www.nuget.org/packages/Svg/3.4.5)  - **FAILS** with - "Error: 0 : Error loading image: 'https://www.w3.org/Icons/SVG/svg-logo-v.png', error: The header name 'image/svg+xml' has an invalid format."

Nuget version: [3.4.4](https://www.nuget.org/packages/Svg/3.4.4) - Working

**Comment by mrbean-bremen** [comment]
What paltform and framework are you using?

**Comment by rasmus-s** [comment]
@mrbean-bremen - Windows 10 x64 and .Net 7

**Comment by mrbean-bremen** [comment]
@H1Gdev - please also have a look. I will check if I can reproduce the problem later tonight, but given that all tests have been passing I doubt it - so currently I have no real idea what went wrong. Also the error message is quite strange, as it relates to a png, not an svg.

**Comment by rasmus-s** [comment]
I made a simple Console app to reproduce it. 
It can be downloaded here: [SVGTestConsoleApp.zip](https://github.com/svg-net/SVG/files/13378298/SVGTestConsoleApp.zip)

As it can see on this image, the "output"-window shows the error. Note the output svg.png is just black.
![image](https://github.com/svg-net/SVG/assets/8188529/57178f76-96ba-4ec4-a72c-08b3296df120)

**Comment by mrbean-bremen** [comment]
I will make another bugfix release soon, as this was a regression.

**Comment by mrbean-bremen** [comment]
The new release is online.

**Comment by rasmus-s** [comment]
Can confirm its working with latest nuget package. Thanks for fast actions 👍
