### ISSUE TITLE
Error rendering element when style (Stroke/Fill etc.) value is "none"

### ISSUE THREAD

**Issue by haykpetros** [svg-net/SVG#114]
When trying to get a preview of SVG (https://gist.github.com/haykpetros/7a639b1b6628a55dd9a9) you get exception on Line 145 of SvgPath.cs. The reason is that "this.MarkerStart" won't be null as it's value is "none", but won't render anything so it fails

**Comment by ravjak** [comment]
I got the same, simple solution is to remove all "marker.*:none;". Svg was done in inkscape
Or add a "fix" to SvgPath.cs:144
                SvgMarker marker = this.OwnerDocument.GetElementById<SvgMarker>(this.MarkerStart.ToString());
                if (marker != null)
                {
                    marker.RenderMarker(renderer, this, path.PathPoints[0], path.PathPoints[0], path.PathPoints[1]);
                }

**Comment by tebjan** [comment]
@ravjak would you be able to provide such a pull request? https://help.github.com/articles/using-pull-requests/

would halp a lot of others with the same probelem... thanks!

**Comment by haykpetros** [comment]
I didn't have access to source, otherwise would fix it myself. I think it will be great if NuGet package can be updated with few recent fixes as well.

**Comment by ravjak** [comment]
I will try to prepare a pull request. But this might be a problem since I have not done it before and to be able to open this project solution in VS 2012 Express I had to remove Test dir. Will let you know tomorrow.

**Comment by tebjan** [comment]
@haykpetros you don't need access to this repository. GitHub works in a way that you fork the repository with your github account and then fix the bugs in your personal repository and open a pull request for the original repository when finished.

**Comment by mrbean-bremen** [comment]
Has been fixed with #183.

**Comment by mrbean-bremen** [comment]
Is broken again, at least since 3.0 - reopen.

**Comment by H1Gdev** [comment]
@mrbean-bremen 
I also fixed this issue with #792.

**Comment by mrbean-bremen** [comment]
Closing as fixed.
