### ISSUE TITLE
Readme and documentation completely ommit what the project is all about

### ISSUE THREAD

**Issue by jovton** [svg-net/SVG#1160]
#### Description

Scanning through the README and the online documentation, I can't seem to find any description of what problem this project/library is supposed to solve. It talks about it being a fork from some project on codeplex (which no longer exists), and some history about the owner and organization transfer, et al, but nothing about why people should use this code. Could someone please add some introductory information to the README and documentation that properly describes what this project is all about, and what problems it solves for its users, with some example code. That would be great, thanks! :)

**Comment by mrbean-bremen** [comment]
All true. The problem is that there is currently no one competent enough and with enough time at hand to write this documentation. 
I made a PR (#1161) that slightly adapts the README (though it doesn't add any documentation), please have a look.

**Comment by jovton** [comment]
thank you @mrbean-bremen, your pull request addresses a reasonable amount of my concerns. i hope your PR can be approved in time! 😄

**Comment by jovton** [comment]
README improved.
