### ISSUE TITLE
Provide ability to insert javascript in SVG

### ISSUE THREAD

**Issue by danielwalls** [svg-net/SVG#167]
I can't see anything in the library that would allow me to generate a javascript section. ie.

```
<svg>
    <script type="text/javascript">
        // <![CDATA[

        // ]]>
    </script>
</svg>
```

As an aside - is there any forum/documentation/wiki that helps people get started using this library? I have a number of questions to ask someone and I'm keen to contribute as well. Is there anyone to contact?

**Comment by Emasoft** [comment]
Why do you want to use javascript for add interativity in SVG? SVG already provides an excellent set of animation and interactive functions called SMIL. You can see a lot of examples on codepen:
http://codepen.io/search?q=smil&limit=all&depth=everything&show_forks=false

I agree that this SVG library should provide support for SMIL. Many animation packages edit and save directly in SMIL. With SMIL support you can do in minutes things that would require days to do in code.

**Comment by tebjan** [comment]
there is now a wiki... if you have helpful information please add it there. if you want to contribute just open a pull request.

**Comment by gvheertum** [comment]
Sorry for necromancing an old issue, but since I also use a lot of SVG's with scripting this issue was something I wanted to fix anyway :)

**Comment by mrbean-bremen** [comment]
Closing as support for `script` tag has been added.
