### ISSUE TITLE
Use ExCSS_Core as parser instead of embedded ExCSS code

### ISSUE THREAD

**Issue by mrbean-bremen** [svg-net/SVG#596]
This is a spin-off of #563 (which grew too long and has more than this subject). 
As discussed [there](https://github.com/vvvv/SVG/issues/563#issuecomment-543711186), it makes sense to use [ExCSS_Core](https://github.com/HockeyJustin/ExCSS_Core) instead of the embedded and changed ExCSS.
As far as I can see, this includes:
- [ ] decide if we will really do this (this may be the only point...)
- [ ] make one or more PRs in ExCSS_Core for fixes/changes that have been made in our code
- [ ] make a PR to add multi-framework support to ExCSS_Core
- [ ] after a new nuget release, remove ExCSS, add the package reference and adapt references where needed 
- [ ] adapt licensing part in Readme

**Comment by H1Gdev** [comment]
@mrbean-bremen 

HockeyJustin/ExCSS_Core#4 is closed...
