### ISSUE TITLE
Try drawing with Svg.Skia

### ISSUE THREAD

**Issue by tebjan** [svg-net/SVG#607]
This could be an option to get cross platform drawing via Skia. We could join efforts with their repository.
https://github.com/mono/SkiaSharp.Extended/tree/master/SkiaSharp.Extended.Svg

This would leave this repo with the task of building and manipulating SVG files. see #590 
But we would need to see how the tests are doing with their renderer.

**Comment by tebjan** [comment]
a better project which is also based on this repo seems to be: https://github.com/wieslawsoltes/Svg.Skia

**Comment by wieslawsoltes** [comment]
I think the solution in Svg.Skia is not really applicable here as it's far more complex. That said the rendering model is based one to one mapping from SkiaSharp so one can create new rendering engine with relative ease (I have create one for SkiaSharp and one for AvaloniaUI).

Reference: https://github.com/wieslawsoltes/Svg.Skia/tree/master/src/Svg.Model
