### ISSUE TITLE
Opacity not correctly inherited

### ISSUE THREAD

**Issue by mrbean-bremen** [svg-net/SVG#777]
This has been working in 3.1.1, broken in master. Can be seen in `__issue-541-01.svg`: The rectangles inherit the opacity 0.5 from the group, but are not displayed at all.

**Comment by mrbean-bremen** [comment]
This has been introduced in [this commit](https://github.com/vvvv/SVG/commit/3fa36ace805b8ec5b9ab25269884ecd4f4afd69b).
@H1Gdev - can you please have a look?

**Comment by H1Gdev** [comment]
@mrbean-bremen 
It's been a long time !!
What is the negative effect of merging which PR ?

**Comment by H1Gdev** [comment]
@mrbean-bremen 
I understand this issue.
I will continue to consider the solution.

**Comment by mrbean-bremen** [comment]
Ah, good to see you again :)

> It's been a long time !!

I had decided to wait with the project until the transistion to the new organization is done - though that didn't happen at that time (it happened today), and I already had decided to leave this behind... Then I wrote a [small tool](https://github.com/mrbean-bremen/ghrepo-stats) to show open issues in a repo, and [used it for the SVG repo](https://raw.githubusercontent.com/mrbean-bremen/ghrepo-stats/master/doc/images/issues.jpg).
After seeing that curve I felt guilty and decided to have another go...
