### ISSUE TITLE
Invalid bmp conversion rendering

### ISSUE THREAD

**Issue by TIPConsulting** [svg-net/SVG#785]
#### Description

Svg file is not being properly rendered when converted to bmp.  Svg file produces desired results in chrome/edge.  The image should have 4 stacked squares.  The top square should be brown and the rest should be blue.  When using vvvv/svg to render as bmp, the top brown square is not included.  The space is transparent instead.  I can see where the brown square should be, but it's like that component is being completely ignored.  The results are the same at any size from 16x16 to 256x256

#### Example data

SVG source file (github wouldnt let me upload an svg, so its a zip):
[Plywood_Logo_SuperSimple.zip](https://github.com/vvvv/SVG/files/5779980/Plywood_Logo_SuperSimple.zip)

Bmp output file:
[256.zip](https://github.com/vvvv/SVG/files/5779982/256.zip)

#### Used Versions
svg 3.1.1
.net 5.0.1
Win10

**Comment by mrbean-bremen** [comment]
For reference - rendered in browser (Chrome):
![grafik](https://user-images.githubusercontent.com/4623701/105085986-d92bfe80-5a98-11eb-9e7d-bb1b9ea99d66.png)
Rendered in SVGViewer:
![grafik](https://user-images.githubusercontent.com/4623701/105086013-e517c080-5a98-11eb-9547-5f4536cde19e.png)

**Comment by mrbean-bremen** [comment]
The problem seems to be `stroke-width: 0px;` in the last polyline, that is drawing the brown square - removing it (or replacing it with `stroke-width: 1px;`) fixes the problem. The stroke width of 0 should not prevent filling, of course...

**Comment by mrbean-bremen** [comment]
A dumbed down version that shows the problem:
```
<?xml version="1.0" encoding="utf-8"?>
<svg viewBox="0 0 50 50" xmlns="http://www.w3.org/2000/svg">
  <polyline style="stroke: none; fill: red; stroke-width: 0px;" points="2 13 27 25 51 13 27 2 7 12"/>
</svg>
```
