### ISSUE TITLE
Bounds for SvgPath don't take transforms into account

### ISSUE THREAD

**Issue by birneamstiel** [svg-net/SVG#830]
#### Description
PR  #282 (Issue #281) introduced the logic for applying transforms to `SvgPathBasedElement`s. Since `SvgPath` overrides the `Bounds` getter and simply returns `this.Path(null).GetBounds()` it bypasses possible transforms. Is this intended? 
If it is not I would propose simply removing the getter for `SvgPath` and fall back to the `SvgPathBasedElement `'s one. I could create a PR accordingly...

**Comment by mrbean-bremen** [comment]
Sorry for the long delay...
I don't think this was intended (I made that PR, but I don't actually remember it...), so please go ahead and make a PR if you are still willing!
