### ISSUE TITLE
Additional XXE vulnerabilities

### ISSUE THREAD

**Issue by kimsey0** [svg-net/SVG#872]
#### Description
Despite the work in #870, there seem to still be a few ways to cause SVG.NET to load external resources, even when `SvgDocument.ResolveExternalResources` is set to `false.`

#### Example data
Via image (same as the second example in #869):
```svg
<svg xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
	<image height="71" width="71" xlink:href="https://www.w3.org/Icons/SVG/svg-logo-v.svg" />
</svg>
```
Via text reference:
```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <tref xlink:href="https://www.w3.org/Icons/SVG/svg-logo-v.svg#nonexistent"/>
</svg>

```

#### Used Versions
Master branch.

**Comment by mrbean-bremen** [comment]
Fixed with #873.
