### ISSUE TITLE
Is there a reason SvgDocument.Open(XmlReader) is not exposed?

### ISSUE THREAD

**Issue by IllidanS4** [svg-net/SVG#877]
`SvgDocument.Open` only accepts a `string`, `Stream` or `XmlDocument`, but there is no public overload for reading out of a generic XML, which should be done via `XmlReader`. It seems the overload is there, but it is not public. Is there a reason for it, or could it be exposed?

This would make reading SVG files from other sources much easier. The data could be produced from a text stream or from a possible serialization of the XML infoset other than the standard one, from `XDocument`, `XElement` (and `XmlElement` as well) or `XPathNavigator`, all without having to store the whole document in memory at once. Additionally a custom entity resolver could be used as well.

**Comment by mrbean-bremen** [comment]
Has anyone an idea why this is so? @tebjan, @H1Gdev? Or could we just expose this?

(going over old issues)

**Comment by H1Gdev** [comment]
`Open` methods

- path
  - [public static SvgDocument Open(string path)](https://github.com/svg-net/SVG/blob/a7088cfcb9feb727ff0574d43af93750cc064561/Source/SvgDocument.cs#L321)
  - [public static T Open<T>(string path) where T : SvgDocument, new()](https://github.com/svg-net/SVG/blob/a7088cfcb9feb727ff0574d43af93750cc064561/Source/SvgDocument.cs#L332)
  - [public static T Open<T>(string path, Dictionary<string, string> entities) where T : SvgDocument, new()](https://github.com/svg-net/SVG/blob/a7088cfcb9feb727ff0574d43af93750cc064561/Source/SvgDocument.cs#L344)
- string
  - [public static T FromSvg<T>(string svg) where T : SvgDocument, new()](https://github.com/svg-net/SVG/blob/a7088cfcb9feb727ff0574d43af93750cc064561/Source/SvgDocument.cs#L378)
- Stream
  - [public static T Open<T>(Stream stream) where T : SvgDocument, new()](https://github.com/svg-net/SVG/blob/a7088cfcb9feb727ff0574d43af93750cc064561/Source/SvgDocument.cs#L368)
  - [public static T Open<T>(Stream stream, Dictionary<string, string> entities) where T : SvgDocument, new()](https://github.com/svg-net/SVG/blob/a7088cfcb9feb727ff0574d43af93750cc064561/Source/SvgDocument.cs#L403)
- XmlDocument
  - [public static SvgDocument Open(XmlDocument document)](https://github.com/svg-net/SVG/blob/a7088cfcb9feb727ff0574d43af93750cc064561/Source/SvgDocument.cs#L554)

**Comment by mrbean-bremen** [comment]
Yes, but the issue is about this method:
```cs
private static T Open<T>(XmlReader reader) where T : SvgDocument, new()
```

**Comment by IllidanS4** [comment]
I tried calling it with reflection and all seems fine.

**Comment by H1Gdev** [comment]
I created PR #897.

- Wrap `XmlReader` by supporting [XXE Mitigation](#870).
- `Open` with `entities` cannot be provided.
