### ISSUE TITLE
Dependency on System.ValueTuple 4.5.0

### ISSUE THREAD

**Issue by jgondev** [svg-net/SVG#879]
There's a dependency on that library but it's not used anywhere. Am I missing it or it could be removed?

**Comment by H1Gdev** [comment]
PR #780.

I don't think this dependency is necessary either.
In Linux need ?

**Comment by wieslawsoltes** [comment]
I think it may be needed for older target frameworks.

**Comment by H1Gdev** [comment]
From test result of PR #880, it seems that it is not necessary. (Test passed on `net452` and `net461`.)
