### ISSUE TITLE
Showing incorrect in WPF

### ISSUE THREAD

**Issue by diehell02** [svg-net/SVG#884]
Description:
I have found that some SVG images display incorrectly in WPF. The images are output by Sketch and set the opacity of the whole control.

data is here:
[Asserts.zip](https://github.com/svg-net/SVG/files/6959672/Asserts.zip)

Used Versions:
SVG version: 1.7.6 from nuget.
.NET Core 3.1

**Comment by mrbean-bremen** [comment]
Can you be a bit more specific? What are you seeing? Also, there is no version 1.7.6 on nuget. The latest version is 3.2.3. Are you sure you are using this SVG library?

**Comment by mrbean-bremen** [comment]
Closing - not enough information.
