### ISSUE TITLE
Not working in non-windows platform(svg to png)

### ISSUE THREAD

**Issue by windowzz** [svg-net/SVG#895]
#### Description
its not working in non windows os like linux
getting this exception
Cannot initialize gdi+ libraries. This is likely to be caused by running on a non-Windows OS without proper gdi+ replacement. Please refer to the documentation for more details.

this function is working fine in windows but not in Linux 
 public static Stream ConvertFromSvg(Stream svgStream)
        {
            var pngStream = new MemoryStream();
            try
            {
                byte[] svgBuffer = new byte[(int)svgStream.Length];
                svgStream.Read(svgBuffer, 0, (int)svgStream.Length);
                var svgDocument = Svg.SvgDocument.FromSvg<Svg.SvgDocument>(Encoding.UTF8.GetString(svgBuffer));
                var bitmap = svgDocument.Draw();
                bitmap.Save(pngStream, System.Drawing.Imaging.ImageFormat.Png);
                pngStream.Position = 0;
            }
            catch (Exception ex)
            {
                var msg = ex.Message;
                // throw;
            }
            return pngStream;
        }
![Uploading image.png…]()

**Comment by mrbean-bremen** [comment]
So, did you check the [documentation](http://svg-net.github.io/SVG/doc/Q&A.html#im-getting-a-svggdipluscannotbeloadedexception-if-running-under-linux-or-macos)?

**Comment by windowzz** [comment]
@mrbean-bremen could you plz take a look into this https://github.com/svg-net/SVG/issues/898
