### ISSUE TITLE
Svg to png giving only black and white colors with dotnet core 2.1

### ISSUE THREAD

**Issue by windowzz** [svg-net/SVG#898]
#### Description

Svg to png giving only black and white colors with dotnet core 2.1
below code is working fine with dotnet core 3.1 but not working with dotnet core 2.1
               var path="test.svg";
                var svgDocument = Svg.SvgDocument.Open(path);
                var bitmap = svgDocument.Draw();
                bitmap.Save(path + ".png", ImageFormat.Png);

**Comment by windowzz** [comment]
@mrbean-bremen 
could you plz take a look into this

**Comment by mrbean-bremen** [comment]
Not sure what to look at. Does this happen to all your images? Which version of the library you are using? On what platform you are testing?

**Comment by mrbean-bremen** [comment]
You are using SVG.Core, our library is called just SVG. This is a fork someone made a couple of years ago, and unfortunately didn't bother to adapt the description. Please use the latest version of SVG instead.

**Comment by windowzz** [comment]
@mrbean-bremen  thanks for your quick response
let me try latest version of svg

**Comment by mrbean-bremen** [comment]
Closing as not an issue.
