### ISSUE TITLE
Auto checker finding security issues

### ISSUE THREAD

**Issue by jarno9981** [svg-net/SVG#899]
![Screenshot_20210922-140637_Chrome](https://user-images.githubusercontent.com/53493418/134344564-e3fdadd4-736a-4d3c-97b5-cb54e761a954.jpg)

Meduim level

**Comment by mrbean-bremen** [comment]
Should be fixed in master (see #869 and #872). Will probably leave this open until the release.

**Comment by mrbean-bremen** [comment]
Closing, as the release is out now.

**Comment by jarno9981** [comment]
> Closing, as the release is out now.

Oke
