### ISSUE TITLE
Problem using SVG with LinearGradient when exporting to PNG 

### ISSUE THREAD

**Issue by AlexandreBazeaud** [svg-net/SVG#902]
#### Description
LinearGradient is not correct.
here is the code of it
![image](https://user-images.githubusercontent.com/63203499/135540665-7ef0ed88-b2cf-4f11-ab03-1470e5db5b6f.png)

SVG
![image](https://user-images.githubusercontent.com/63203499/135540134-686956e3-f490-4741-978f-e9f7d7170a30.png)
PNG
![image](https://user-images.githubusercontent.com/63203499/135540311-1797375d-bb57-4132-9a78-154dc84987ff.png)

#### Used Versions

Net 6.0 SVG 3.3.0 on windows

**Comment by mrbean-bremen** [comment]
Can you upload the SVG as code (not as a screenshot) to be able to reproduce this? Also, what do the 2 pictures (SVG/PNG) show? They look identical to me.

**Comment by AlexandreBazeaud** [comment]
You can see that the background is not the same at skyline level.
Here is the svg https://pastebin.com/XaZ6ALG9

**Comment by mrbean-bremen** [comment]
Thanks - for some reason I didn't see the difference the first time.

**Comment by AlexandreBazeaud** [comment]
Sorry for sending a message here, but i'm wondering, when will this update be on nuget ? or is there any beta channel where i can have it ? would be cool to have it now.
