### ISSUE TITLE
SVG to PNG renders inline images incorrectly

### ISSUE THREAD

**Issue by KoalaBear84** [svg-net/SVG#917]
#### Description
I'm trying to convert an online Meteogram from SVG to PNG. It looks like it doesn't scale the inline (base64) images down correctly.

#### Example data
Url: https://developer.yr.no/doc/assets/meteogram.svg

Expected:
![image](https://user-images.githubusercontent.com/5886900/138819972-36a75ac4-61ea-4ff9-b220-ce2bae10779d.png)

Result:
![image](https://user-images.githubusercontent.com/5886900/138819846-93e3426a-b053-4c60-9a63-ba65ddbdc71b.png)

Example code:
```csharp
using Svg;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Net.Http;
using System.Threading.Tasks;

namespace SvgConvert
{
    public class Program
    {
        public static async Task Main()
        {
            HttpClient httpClient = new HttpClient();
            Stream httpSvgStream = await httpClient.GetStreamAsync("https://developer.yr.no/doc/assets/meteogram.svg");
            SvgDocument svgDocument = SvgDocument.Open<SvgDocument>(httpSvgStream);
            Bitmap bitmap = svgDocument.Draw();
            bitmap.Save("Meteogram.png", ImageFormat.Png);
        }
    }
}
```

Maybe the issue is only scaling and it could be an easy fix. Or there is more info in the <style> tags which isn't parsed/respected.

#### Used Versions
Windows 10 Pro 21H1 19043.1288
Svg 3.3.0
.NET 6.0 (Also tried .NET Core 3.1 and .NET 5.0)

**Comment by KoalaBear84** [comment]
Thanks @mrbean-bremen 👍
I'll check it when a new release is out.

**Comment by mrbean-bremen** [comment]
You'll have to thank @H1Gdev who fixed it 😄

**Comment by KoalaBear84** [comment]
Yes indeed, I did saw it 😬

Thanks @H1Gdev 👍
