### ISSUE TITLE
Rendering to a bitmap causes the SVG lines to look thicker than in Chrome

### ISSUE THREAD

**Issue by RobotGizmo** [svg-net/SVG#926]
#### Description
When rendering an SVG file as a bitmap at 16px the rendered version looks much thicker than when viewed in Chrome at the same size. I have attached an image showing the comparison between this library and Chrome. Is there anything I can do to tweak the output to have it match? Thanks!

#### Example data
![SvgCompare](https://user-images.githubusercontent.com/6288105/144917109-5fbbbef3-8d73-403f-b447-eb78efddc434.png)

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
	<path d="M256 0C114.6 0 0 114.6 0 256s114.6 256 256 256s256-114.6 256-256S397.4 0 256 0zM256 464c-114.7 0-208-93.31-208-208S141.3 48 256 48s208 93.31 208 208S370.7 464 256 464zM256 336c-18 0-32 14-32 32s13.1 32 32 32c17.1 0 32-14 32-32S273.1 336 256 336zM289.1 128h-51.1C199 128 168 159 168 198c0 13 11 24 24 24s24-11 24-24C216 186 225.1 176 237.1 176h51.1C301.1 176 312 186 312 198c0 8-4 14.1-11 18.1L244 251C236 256 232 264 232 272V288c0 13 11 24 24 24S280 301 280 288V286l45.1-28c21-13 34-36 34-60C360 159 329 128 289.1 128z"/>
</svg>`

#### Used Versions
NuGet v3.3.0
Windows 11 x64
.NET 4.6.2

**Comment by H1Gdev** [comment]
> When rendering an SVG file as a bitmap at 16px the rendered version

How do you do it ?

**Comment by RobotGizmo** [comment]
Sorry to report this, it looks like the issue was with replacing the colours. It didn't maintain the alpha channel value of the colour so it made the edges blocky. I re-wrote the colour replacing code to keep the alpha value and use the new colour's RGB values and it's looking much better now. Thanks for the quick response and sorry for the ticket. Keep up the great work!
