### ISSUE TITLE
Multiple TextDecoration flags result in commas when serializing to .svg

### ISSUE THREAD

**Issue by zerg960** [svg-net/SVG#941]
#### Description
When using multiple Text Decorations, the serialized .svg file has commas in between each text decoration flag. This causes renderers (the .svg file as well as .bmp) to not render the text decorations.

#### Example data

```C#
var svg = new SvgDocument
{
    Width = 300,
    Height = 100,
    ViewBox = new SvgViewBox(0, 0, 300, 100),
    Children =
    {
        new SvgText("Hello World!")
        {
            Y = {50},
            FontSize = 50,
            TextDecoration = SvgTextDecoration.LineThrough | SvgTextDecoration.Underline |
                             SvgTextDecoration.Overline
        }
    }
};

using var bitmap = svg.Draw();
bitmap.Save("card.bmp", ImageFormat.Bmp);
svg.Write("card.svg");
```

Resulting SVG:

```svg
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xml="http://www.w3.org/XML/1998/namespace" width="300" height="100" viewBox="0, 0, 300, 100">
  <text y="50" font-size="50" text-decoration="underline, overline, line-through">Hello World!</text>
</svg>
```

`text-decoration="underline, overline, line-through"` should read `text-decoration="underline overline line-through"`

#### Used Versions
NuGet version 3.4.0 (released 3 days ago), Windows 10, Target Framework .NET 5.0

**Comment by mrbean-bremen** [comment]
Seems to be a problem with bit flag enums, which are converted to string using the standard `ToString()` method, which inserts the commas for combined flags. `SvgTextDecoration` (this case) seems to be only such type that can have combined values so far.

**Comment by mrbean-bremen** [comment]
Note that `SvgTextDecoration.Overline` is currently not supported in rendering (as it is not supported by `System.Drawing``).
