### ISSUE TITLE
RequiresSmoothRendering is always false for an SvgRectangle if CornerRadiusX and CornerRadiusY are 0

### ISSUE THREAD

**Issue by supranowitz** [svg-net/SVG#960]
#### Description
Anti-aliasing is never used for a simple rectangle without rounded corners, but forcing anti-aliasing to be enabled improves the rendering.  I do not quite understand the reasoning for the logic in SvgRectangle.  

Currently, RequiresSmoothRendering is implemented like this:

```
        protected override bool RequiresSmoothRendering
        {
            get
            {
                if (base.RequiresSmoothRendering)
                    return (CornerRadiusX.Value > 0.0f || CornerRadiusY.Value > 0.0f);
                else
                    return false;
            }
        }
```

But this would make more sense to me (no matter what base.RequiresSmoothRendering returns, force it on if corners are rounded):
```
        protected override bool RequiresSmoothRendering
        {
            get
            {
                if (!base.RequiresSmoothRendering)
                    return (CornerRadiusX.Value > 0.0f || CornerRadiusY.Value > 0.0f);
                else
                    return true;
            }
        }
```

#### Example data

| SVG | svg-net rendering |
| ----------- | ----------- |
| [Rectangles](https://user-images.githubusercontent.com/64907346/158681119-35009cf9-012d-4a51-b711-c6efc8069bf4.svg)| <img width="21" alt="rectangles" src="https://user-images.githubusercontent.com/64907346/158680309-e3c41283-1344-43f3-985b-223ba2464cc4.png">|
| [Rectangles with corner radius](https://user-images.githubusercontent.com/64907346/158681166-796b0742-5346-48a2-9767-f045cc484b0f.svg)| <img width="21" alt="rectangles-rounded" src="https://user-images.githubusercontent.com/64907346/158680998-4be58e10-c7b6-4564-a7cd-55454173d47e.png">|

When the original svg is rendered to a small bitmap the spacing and bottom vertical alignment does not appear to be consistent, but the rendering is improved when anti-aliasing is forced to be on by adding a very small corner radius to the rectangles.

#### Used Versions

SVG 3.3.0
.NET Framework 4.8

**Comment by H1Gdev** [comment]
Condition for anti-aliasing in `SvgRectangle` have been around since early days.

https://github.com/svg-net/SVG/blob/cf59fef87fbac69ed12f51123f85a7ac363b29d2/Source/Basic%20Shapes/SvgRectangle.cs#L103

**Comment by mrbean-bremen** [comment]
Ok, I did a few tests, and Chrome, FireFox and Edge agree on the handling (IE seems not to handle `shape-rendering`). If `shape-rendering` is set to `auto` or `geometricPrecision`, they use anti-aliasing for the rectangles, if set to `optimizeSpeed` or `crispEdges` they don't use it, regardless of rounded edges. The same seems to be true for other shapes. So to conform to these, we would have to change the base implementation to use anti-aliasing also for `geometricPrecision`, and remove the overload for `Rectangle`.
Any thoughts?

**Comment by H1Gdev** [comment]
@mrbean-bremen 

I agree with your view.

To check effect of `anti-aliasing`, I used the following simple SVGs.

```svg
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="500" height="260">
  <rect x="20"  y="20"  width="100" height="100" rx="40" ry="40" fill="red" shape-rendering="auto" />
  <rect x="140" y="20"  width="100" height="100" rx="40" ry="40" fill="red" shape-rendering="optimizeSpeed" />
  <rect x="260" y="20"  width="100" height="100" rx="40" ry="40" fill="red" shape-rendering="crispEdges" />
  <rect x="380" y="20"  width="100" height="100" rx="40" ry="40" fill="red" shape-rendering="geometricPrecision" />

  <rect x="20"  y="140" width="100" height="100"                 fill="red" shape-rendering="auto" />
  <rect x="140" y="140" width="100" height="100"                 fill="red" shape-rendering="optimizeSpeed" />
  <rect x="260" y="140" width="100" height="100"                 fill="red" shape-rendering="crispEdges" />
  <rect x="380" y="140" width="100" height="100"                 fill="red" shape-rendering="geometricPrecision" />
</svg>
```

```svg
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="790" viewBox="0 0 500 260">
  <rect x="20"  y="20"  width="100" height="100"                 fill="red" shape-rendering="auto" />
  <rect x="140" y="20"  width="100" height="100"                 fill="red" shape-rendering="optimizeSpeed" />
  <rect x="260" y="20"  width="100" height="100"                 fill="red" shape-rendering="crispEdges" />
  <rect x="380" y="20"  width="100" height="100"                 fill="red" shape-rendering="geometricPrecision" />
</svg>
```

**Comment by mrbean-bremen** [comment]
Consider fixed, as it now bahaves like in browsers, and the standard is not very specific about the implementation.
