### ISSUE TITLE
SVG 3.4.2 version SvgDocument Draw Out of memory

### ISSUE THREAD

**Issue by DebbieGao** [svg-net/SVG#978]
#### Description

When update to svg 3.4.2, the svgDocument.Draw() throw exception, out of memory.
If use version 3.4.0, it is OK. 
#### Used Versions

SVG 3.4.2
.net standard 2.0

**Comment by mrbean-bremen** [comment]
Can you show the image that causes that? Or does this happen for all images?

**Comment by DebbieGao** [comment]
> Can you show the image that causes that? Or does this happen for all images?

That is a really specific image, which is .svg and about 1100KB. I did not try other images.

**Comment by H1Gdev** [comment]
@DebbieGao 

Can you publish SVG file ?

**Comment by DebbieGao** [comment]
> 

sorry, I cannot publish it.

**Comment by H1Gdev** [comment]
The tendency is that `gradation` seems to be out of memory.
Is it possible to create minimum SVG that will fail ?

**Comment by wshiadai** [comment]
I have  the same problem
this is my demo code
` private void btnSVG2_Click(object sender, EventArgs e)
        {
            try
            {
                var svgDoc = SvgDocument.Open<SvgDocument>(path);
                Bitmap bmp = svgDoc.Draw();
                bmp.Save(@"D:\Liu\Project\DataPenetrationDemo\DataPenetrationDemo\Static\liu002.png");
                bmp.Dispose();
                MessageBox.Show("SVG已生成图片");
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
           
        }`
result：
![image](https://user-images.githubusercontent.com/1819491/177458470-d406ae59-b19f-4ec0-83d0-bd671fb35e4c.png)

my svg file:
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 66.81 66.68">
    <defs>
        <linearGradient id="未命名的渐变_7" x1="21.39" y1="33.34" x2="45.3" y2="33.34" gradientUnits="userSpaceOnUse">
            <stop offset="0" stop-color="#32343d"/>
            <stop offset="0.13" stop-color="#18121c"/>
            <stop offset="0.55" stop-color="#434652"/>
            <stop offset="0.63" stop-color="#3f414d"/>
            <stop offset="0.74" stop-color="#32323d"/>
            <stop offset="0.86" stop-color="#1e1924"/>
            <stop offset="0.87" stop-color="#1d1822"/>
        </linearGradient>
        <linearGradient id="未命名的渐变_508" x1="33.35" y1="8.62" x2="33.35" y2="7.68" gradientUnits="userSpaceOnUse">
            <stop offset="0.13" stop-color="#1d1822"/>
            <stop offset="0.14" stop-color="#1e1924"/>
            <stop offset="0.26" stop-color="#32323d"/>
            <stop offset="0.37" stop-color="#3f414d"/>
            <stop offset="0.45" stop-color="#434652"/>
            <stop offset="0.87" stop-color="#18121c"/>
            <stop offset="1" stop-color="#32343d"/>
        </linearGradient>
        <linearGradient id="未命名的渐变_7-2" x1="33.33" y1="58.99" x2="33.33" y2="58.06" xlink:href="#未命名的渐变_7"/>
        <linearGradient id="未命名的渐变_508-2" x1="5486.66" y1="-5510.26" x2="5486.66" y2="-5541.03" gradientTransform="matrix(1, 0, 0, -1, -5453.32, -5520.98)" xlink:href="#未命名的渐变_508"/>
        <linearGradient id="未命名的渐变_73" x1="5486.66" y1="-5517.59" x2="5486.66" y2="-5540.14" gradientTransform="matrix(0, 1, 1, 0, 5558.99, -5482)" gradientUnits="userSpaceOnUse">
            <stop offset="0.13" stop-color="#484354"/>
            <stop offset="0.25" stop-color="#5a596a"/>
            <stop offset="0.36" stop-color="#67697a"/>
            <stop offset="0.45" stop-color="#6b6e7f"/>
            <stop offset="0.87" stop-color="#302537"/>
            <stop offset="1" stop-color="#545565"/>
        </linearGradient>
        <linearGradient id="未命名的渐变_508-3" x1="5544.02" y1="-5510.28" x2="5544.02" y2="-5541.05" gradientTransform="matrix(1, 0, 0, -1, -5510.69, -5463.65)" xlink:href="#未命名的渐变_508"/>
        <linearGradient id="未命名的渐变_73-2" x1="5544.02" y1="-5517.61" x2="5544.02" y2="-5540.16" gradientTransform="matrix(1, 0, 0, -1, -5513.91, -5466.87)" xlink:href="#未命名的渐变_73"/>
        <linearGradient id="未命名的渐变_508-4" x1="7.7" y1="33.33" x2="8.63" y2="33.33" xlink:href="#未命名的渐变_508"/>
        <linearGradient id="未命名的渐变_508-5" x1="17.47" y1="45.29" x2="17.47" y2="21.37" xlink:href="#未命名的渐变_508"/>
        <linearGradient id="未命名的渐变_508-7" x1="1604.31" y1="57.92" x2="1604.31" y2="27.15" gradientTransform="matrix(1, 0, 0, -1, -1599.65, 75.87)" xlink:href="#未命名的渐变_508"/>
        <linearGradient id="未命名的渐变_73-3" x1="1604.31" y1="50.58" x2="1604.31" y2="28.04" gradientTransform="matrix(1, 0, 0, -1, -1599.65, 69.43)" xlink:href="#未命名的渐变_73"/>
        <linearGradient id="未命名的渐变_508-8" x1="58.1" y1="33.33" x2="59.04" y2="33.33" xlink:href="#未命名的渐变_508"/>
        <linearGradient id="未命名的渐变_508-9" x1="2061.22" y1="45.29" x2="2061.22" y2="21.37" gradientTransform="matrix(1.01, 0, 0, -1, -2037.22, 66.66)" xlink:href="#未命名的渐变_508"/>
        <linearGradient id="未命名的渐变_7-3" x1="58.1" y1="33.33" x2="59.04" y2="33.33" xlink:href="#未命名的渐变_7"/>
        <linearGradient id="未命名的渐变_508-10" x1="-439.47" y1="57.91" x2="-439.47" y2="27.14" gradientTransform="translate(506.95 -9.19) scale(1.01 1)" xlink:href="#未命名的渐变_508"/>
        <linearGradient id="未命名的渐变_73-4" x1="-439.47" y1="50.58" x2="-439.47" y2="28.03" gradientTransform="translate(506.95 -9.19) scale(1.01 1)" xlink:href="#未命名的渐变_73"/>
        <linearGradient id="未命名的渐变_7-4" x1="21.35" y1="0.82" x2="45.35" y2="0.82" xlink:href="#未命名的渐变_7"/>
        <linearGradient id="未命名的渐变_7-5" x1="21.33" y1="65.86" x2="45.33" y2="65.86" xlink:href="#未命名的渐变_7"/>
        <linearGradient id="未命名的渐变_508-11" x1="-793.23" y1="-1170.07" x2="-769.23" y2="-1170.07" gradientTransform="translate(1170.89 -747.89) rotate(-90)" xlink:href="#未命名的渐变_508"/>
        <linearGradient id="未命名的渐变_508-12" x1="-793.22" y1="-1104.9" x2="-769.22" y2="-1104.9" gradientTransform="translate(1170.89 -747.89) rotate(-90)" xlink:href="#未命名的渐变_508"/>
    </defs>
    <g style="isolation:isolate">
        <g id="图层_2" data-name="图层 2">
            <g id="图层_1-2" data-name="图层 1">
                <rect x="21.39" y="7.68" width="23.92" height="51.31" style="fill:url(#未命名的渐变_7)"/>
                <rect x="21.39" y="7.68" width="23.92" height="0.93" style="fill:url(#未命名的渐变_508)"/>
                <rect x="21.37" y="58.06" width="23.92" height="0.93" style="fill:url(#未命名的渐变_7-2)"/>
                <rect x="30.32" y="-10.72" width="6.04" height="30.77" transform="translate(38.01 -28.68) rotate(90)" style="fill:url(#未命名的渐变_508-2)"/>
                <polygon points="41.4 6.78 41.4 2.54 18.85 2.54 18.85 6.78 18.85 6.78 41.4 6.78" style="fill:url(#未命名的渐变_73)"/>
                <rect x="30.31" y="46.63" width="6.04" height="30.77" transform="translate(95.34 28.68) rotate(90)" style="fill:url(#未命名的渐变_508-3)"/>
                <rect x="27.99" y="50.74" width="4.24" height="22.55" transform="translate(92.12 31.9) rotate(90)" style="fill:url(#未命名的渐变_73-2)"/>
                <g style="mix-blend-mode:multiply">
                    <rect x="7.7" y="21.37" width="0.93" height="23.92" style="fill:url(#未命名的渐变_508-4)"/>
                </g>
                <path d="M7.68,21.37H21.09a6.17,6.17,0,0,1,6.17,6.17V39.12a6.17,6.17,0,0,1-6.17,6.17H7.68a0,0,0,0,1,0,0V21.37A0,0,0,0,1,7.68,21.37Z" style="fill:url(#未命名的渐变_508-5)"/>
                <rect x="7.7" y="21.37" width="0.93" height="23.92" style="fill:url(#未命名的渐变_508-4)"/>
                <rect x="1.64" y="17.95" width="6.04" height="30.77" transform="translate(9.32 66.68) rotate(180)" style="fill:url(#未命名的渐变_508-7)"/>
                <rect x="2.54" y="18.84" width="4.24" height="22.55" transform="translate(9.32 60.24) rotate(180)" style="fill:url(#未命名的渐变_73-3)"/>
                <g style="mix-blend-mode:multiply">
                    <rect x="58.1" y="21.37" width="0.95" height="23.92" style="fill:url(#未命名的渐变_508-8)"/>
                </g>
                <path d="M39.24,21.37H52.85a6.21,6.21,0,0,1,6.21,6.21V39.08a6.21,6.21,0,0,1-6.21,6.21H39.24a0,0,0,0,1,0,0V21.37A0,0,0,0,1,39.24,21.37Z" transform="translate(98.29 66.66) rotate(180)" style="fill:url(#未命名的渐变_508-9)"/>
                <rect x="58.1" y="21.37" width="0.95" height="23.92" style="fill:url(#未命名的渐变_7-3)"/>
                <rect x="59.06" y="17.94" width="6.12" height="30.77" style="fill:url(#未命名的渐变_508-10)"/>
                <polygon points="64.26 41.38 59.97 41.38 59.97 18.84 59.97 18.84 64.26 18.84 64.26 18.84 64.26 41.38" style="fill:url(#未命名的渐变_73-4)"/>
                <rect x="21.35" width="24" height="1.64" style="fill:url(#未命名的渐变_7-4)"/>
                <rect x="21.33" y="65.03" width="24" height="1.64" style="fill:url(#未命名的渐变_7-5)"/>
                <rect y="21.34" width="1.64" height="24" style="fill:url(#未命名的渐变_508-11)"/>
                <rect x="65.17" y="21.33" width="1.64" height="24" style="fill:url(#未命名的渐变_508-12)"/>
            </g>
        </g>
    </g>
</svg>`

**Comment by H1Gdev** [comment]
Can you output contents of this exception as well ?
(I especially want to know call stack.)

**Comment by H1Gdev** [comment]
@DebbieGao 
@wshiadai 

3.4.3 has been released.
This version should fix this issue.
Please check with latest version.

**Comment by wshiadai** [comment]
> 

Thank you very much :)

**Comment by wshiadai** [comment]
> Can you output contents of this exception as well ? (I especially want to know call stack.)

Sorry for not replying in time, this issue has been resolved

**Comment by mrbean-bremen** [comment]
Closing as resolved.
