### ISSUE TITLE
Failed to install Svg 3.4.0 with target .NET 4.5

### ISSUE THREAD

**Issue by shark20609** [svg-net/SVG#992]
Error cannot install package 'Svg 3.4.0'. You are trying to install this package to the target of ". NETFramework, Version=v4.5 " project, but the package does not contain any assembly references or content files compatible with the framework

**Comment by mrbean-bremen** [comment]
Please write in English, otherwise we won't understand you.

**Comment by shark20609** [comment]
Error cannot install package 'Svg 3.4.0'. You are trying to install this package to the target of ". NETFramework, Version=v4.5 " project, but the package does not contain any assembly references or content files compatible with the framework

**Comment by H1Gdev** [comment]
@shark20609 

.NET Framework 4.5 is no longer supported.
https://dotnet.microsoft.com/download/visual-studio-sdks

**Comment by paulushub** [comment]
.NET Framework 4.5 is no longer supported.
